In [3]:
import pandas as pd

In [4]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.array

<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2["a"]

-5

In [9]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [10]:
"b" in obj2

True

In [11]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [12]:
obj3 = pd.Series(sdata)

In [13]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [14]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [15]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [16]:
obj4 = pd.Series(sdata, index=states)

In [17]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [18]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [19]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [20]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [22]:
obj4.name = "population"

In [23]:
obj4.index.name = "state"


In [24]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [25]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]

In [26]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [27]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [28]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [29]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [30]:
frame.tail()


state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [31]:
pd.DataFrame(data, columns=["year", "state", "pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [32]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

In [33]:
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [34]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [35]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [36]:
frame2["debt"] = 16.5

In [38]:
import numpy as np
frame2["debt"] = np.arange(6.)

In [40]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [42]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

In [43]:
frame2["debt"] = val
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [44]:
frame2["eastern"] = frame2["state"] == "Ohio"

In [45]:
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [46]:
del frame2["eastern"]

In [47]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},"Nevada": {2001: 2.4, 2002: 2.9}}

In [49]:
frame3 = pd.DataFrame(populations)

In [50]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [51]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [52]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [53]:
pdata = {"Ohio": frame3["Ohio"][:-1],"Nevada": frame3["Nevada"][:2]}

In [54]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [55]:
frame3.index.name = "year"

In [56]:
frame3.columns.name = "state"

In [57]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [58]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [59]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [60]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

In [61]:
index = obj.index


In [62]:
index

Index(['a', 'b', 'c'], dtype='object')

In [63]:
labels = pd.Index(np.arange(3))

In [64]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [65]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [66]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [67]:
"Ohio" in frame3.columns

True

In [68]:
2003 in frame3.index

False

In [69]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [70]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

In [71]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

In [72]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [73]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [74]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [75]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),index=["a", "c", "d"],columns=["Ohio", "Texas", "California"])

In [76]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [77]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [78]:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [79]:
frame.reindex(states, axis="columns")

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [80]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

California  Texas
a           2      1
d           8      7
c           5      4

In [83]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [84]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [85]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [88]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"])

In [89]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [90]:
data.drop(index=["Colorado", "Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [92]:
data.drop("two", axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [93]:
data.drop(["two", "four"], axis="columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [94]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])

In [95]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [96]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [97]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [98]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [99]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [100]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [101]:
obj2[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [102]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [103]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [104]:
obj2.loc["b":"c"] = 5
obj2

a    1
b    5
c    5
dtype: int64

In [105]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=["Ohio", "Colorado", "Utah", "New York"],columns=["one", "two", "three", "four"])

In [106]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [107]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [108]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [109]:
data[data["three"] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [110]:
data[data < 5] = 0


In [111]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [112]:
data.loc["Colorado"]


one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [113]:
data.loc["Colorado", ["two", "three"]]


two      5
three    6
Name: Colorado, dtype: int64

In [114]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [115]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [116]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [117]:
ser = pd.Series(np.arange(3.))

In [118]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [119]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])

In [120]:
ser.iloc[-1]

2.0

In [121]:
ser2[-1]

2.0

In [122]:
data.loc[:, "one"] = 1

In [123]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [124]:
data.iloc[2] = 5

In [125]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [126]:
data.loc[data["four"] > 5] = 3
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [127]:
data.loc[data.three == 5, "three"] = 6
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

In [128]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=["a", "c", "e", "f", "g"])

In [129]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [130]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [131]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [132]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [133]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [134]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [135]:
df1 = pd.DataFrame({"A": [1, 2]})

In [136]:
df2 = pd.DataFrame({"B": [3, 4]})

In [137]:
df1

A
0  1
1  2

In [138]:
df2

B
0  3
1  4

In [139]:
df1+df2

A   B
0 NaN NaN
1 NaN NaN

In [140]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list("abcde"))
df2.loc[1, "b"] = np.nan

In [141]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [142]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [143]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [144]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [145]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [146]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [147]:
arr = np.arange(12.).reshape((3, 4))

In [148]:
arr[0]

array([0., 1., 2., 3.])

In [149]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [150]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])

In [151]:
series = frame.iloc[0]

In [152]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [153]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [154]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [155]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

In [156]:
series2

b    0
e    1
f    2
dtype: int64

In [157]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [158]:
series3 = frame["d"]

In [159]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [160]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [161]:
frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [162]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])

In [163]:
frame

b         d         e
Utah   -0.706227 -0.039584 -1.503808
Ohio    0.568243 -1.797444 -0.437585
Texas   1.393178 -0.533369 -0.440555
Oregon -2.040323 -0.148968 -0.778472

In [164]:
np.abs(frame)

b         d         e
Utah    0.706227  0.039584  1.503808
Ohio    0.568243  1.797444  0.437585
Texas   1.393178  0.533369  0.440555
Oregon  2.040323  0.148968  0.778472

In [165]:
def f1(x):
  return x.max() - x.min()

frame.apply(f1)

b    3.433500
d    1.757860
e    1.066223
dtype: float64

In [166]:
frame.apply(f1, axis="columns")

Utah      1.464224
Ohio      2.365687
Texas     1.926547
Oregon    1.891355
dtype: float64

In [167]:
def f2(x):
     return pd.Series([x.min(), x.max()], index=["min", "max"])

frame.apply(f2)

b         d         e
min -2.040323 -1.797444 -1.503808
max  1.393178 -0.039584 -0.437585

In [168]:
def my_format(x):
     return f"{x:.2f}"

frame.applymap(my_format)

b      d      e
Utah    -0.71  -0.04  -1.50
Ohio     0.57  -1.80  -0.44
Texas    1.39  -0.53  -0.44
Oregon  -2.04  -0.15  -0.78

In [169]:
frame["e"].map(my_format)

Utah      -1.50
Ohio      -0.44
Texas     -0.44
Oregon    -0.78
Name: e, dtype: object

In [170]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [171]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [172]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),index=["three", "one"],columns=["d", "a", "b", "c"])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [173]:
frame.sort_index(axis="columns", ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [174]:
obj = pd.Series([4, 7, -3, 2])

In [175]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [176]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [177]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [178]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [179]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})

In [180]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [181]:
frame.sort_values("b")

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [182]:
frame.sort_values(["a", "b"])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [183]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [184]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [185]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [186]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],"c": [-2, 5, 8, -2.5]})

In [187]:
frame.rank(axis="columns")

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [188]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

In [189]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [190]:
obj.index.is_unique

False

In [191]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),index=["a", "a", "b", "b", "c"])

In [192]:
df

0         1         2
a  0.833812 -2.063247  1.640102
a -1.248132  0.659157  2.187248
b -1.109654 -1.235077  1.261484
b -0.110968 -0.397235  0.246159
c  0.114221  0.270588  0.457659

In [193]:
df.loc["b"]

0         1         2
b -1.109654 -1.235077  1.261484
b -0.110968 -0.397235  0.246159

In [194]:
df.loc["c"]

0    0.114221
1    0.270588
2    0.457659
Name: c, dtype: float64

In [195]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],index=["a", "b", "c", "d"],columns=["one", "two"])

In [196]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [197]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [198]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [199]:
df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

In [200]:
df.sum(axis="columns", skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [201]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [202]:
df.idxmax()

one    b
two    d
dtype: object

In [203]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [204]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [205]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [206]:
uniques = obj.unique()

In [207]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [208]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [209]:
pd.value_counts(obj.to_numpy(), sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [210]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [211]:
mask = obj.isin(["b", "c"])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [212]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
unique_vals = pd.Series(["c", "b", "a"])
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 2, 1, 1, 0, 2])

In [213]:
In [303]: data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],"Qu2": [2, 3, 1, 2, 3],"Qu3": [1, 5, 2, 4, 4]})

In [214]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [215]:
data["Qu1"].value_counts().sort_index()

1    1
3    2
4    2
Name: Qu1, dtype: int64

In [216]:
result = data.apply(pd.value_counts).fillna(0)

In [217]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [220]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})
data

a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [221]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
dtype: int64